## netlify.toml

[build]
  publish = "out"
  command = "next build && next export"

[[redirects]]
  from = "/users/*"
  to = "/users/[id].html"
  status = 200
  force = true

  from = "/account/activate/*"
  to = "/account/activate/[token].html"
  status = 200
  force = true
